services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./api:/var/www/api
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge